### ISSUE TITLE
Text area expands when clicking out of it

### ISSUE THREAD

**Issue by mrigdon** [janjarfalk/jquery-elastic#28]
If I click in the textarea, don't type any text, and then click out of the textarea, the textarea expands about a row. I'm using the Bootstrap form-control class for my text area.

here's my code:

``` html
        <form action='/create_post/' method="post" id="post-form">
            {% csrf_token %}

            {% with user.first_name|add:" "|add:user.last_name as name %}
              {% render_field post_form.identity hidden="true" value=name %}
            {% endwith %}

            <!-- the following line is the textarea -->
            {% render_field post_form.body class+="form-control" rows="4" placeholder="Say howdy to your neighbors!" %} 

            <div id="comment-row" class="row">
              <button id="comment-submit" type="submit" name="submit" class="btn btn-primary">Post</button>
            </div>
          </form>
```

**Comment by viion** [comment]
Same issue, click in and out, repeat, it continues to expand...

**Comment by janjarfalk** [comment]
The height goal for the textareas is content height plus one line height.
https://github.com/janjarfalk/jquery-elastic/blob/master/jquery.elastic.source.js#L113

It should not expand indefinitely thou. What browser are you using?

**Comment by devuvar** [comment]
the issue is due to usage of .height() at https://github.com/janjarfalk/jquery-elastic/blob/master/jquery.elastic.source.js#L147 while setting height on blur event. 
While getting the height, css() method is used at https://github.com/janjarfalk/jquery-elastic/blob/master/jquery.elastic.source.js#L59.
height() function adds the padding into resulting height.
Using .css to set the height will solve the issue
// Compact textarea on blur
				$textarea.bind('blur',function(){
					if($twin.height() < maxheight){
						if($twin.height() > minheight) {
							$textarea.css('height', $twin.height() + 'px');
						} else {
							$textarea.css('height', minheight + 'px');
						}
					}
				});
